CREATE ROLE mikedegeofroy WITH LOGIN PASSWORD 'flowerpower' CREATEDB INHERIT;

CREATE ROLE itmo_users  NOLOGIN NOCREATEDB NOCREATEROLE INHERIT;
CREATE ROLE itmo_readers NOLOGIN NOCREATEDB NOCREATEROLE INHERIT;

CREATE ROLE itmo_user_1   WITH LOGIN PASSWORD 'user1_pass'   INHERIT;
CREATE ROLE itmo_reader_1 WITH LOGIN PASSWORD 'reader1_pass' INHERIT;

GRANT itmo_users  TO itmo_user_1;
GRANT itmo_readers TO itmo_reader_1;
